# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.srcs/sources_1/bd/design_fix1/ip/design_fix1_rst_clk_wiz_100M_1/design_fix1_rst_clk_wiz_100M_1.xci
# IP: The module: 'design_fix1_rst_clk_wiz_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_rst_clk_wiz_100M_1/design_fix1_rst_clk_wiz_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fix1_rst_clk_wiz_100M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_rst_clk_wiz_100M_1/design_fix1_rst_clk_wiz_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fix1_rst_clk_wiz_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.srcs/sources_1/bd/design_fix1/ip/design_fix1_rst_clk_wiz_100M_1/design_fix1_rst_clk_wiz_100M_1.xci
# IP: The module: 'design_fix1_rst_clk_wiz_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_rst_clk_wiz_100M_1/design_fix1_rst_clk_wiz_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fix1_rst_clk_wiz_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_rst_clk_wiz_100M_1/design_fix1_rst_clk_wiz_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fix1_rst_clk_wiz_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
