transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/xil_defaultlib
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_21
vlib riviera/processing_system7_vip_v1_0_23
vlib riviera/xlconstant_v1_1_10
vlib riviera/proc_sys_reset_v5_0_17
vlib riviera/smartconnect_v1_0
vlib riviera/axi_register_slice_v2_1_35
vlib riviera/axi_bram_ctrl_v4_1_13
vlib riviera/blk_mem_gen_v8_4_11

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap xil_defaultlib riviera/xil_defaultlib
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_21 riviera/axi_vip_v1_1_21
vmap processing_system7_vip_v1_0_23 riviera/processing_system7_vip_v1_0_23
vmap xlconstant_v1_1_10 riviera/xlconstant_v1_1_10
vmap proc_sys_reset_v5_0_17 riviera/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_register_slice_v2_1_35 riviera/axi_register_slice_v2_1_35
vmap axi_bram_ctrl_v4_1_13 riviera/axi_bram_ctrl_v4_1_13
vmap blk_mem_gen_v8_4_11 riviera/blk_mem_gen_v8_4_11

vlog -work xilinx_vip  -incr "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"/home/minami/tools/xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/minami/tools/xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"/home/minami/tools/xilinx/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_ooo_controller_0_0/sim/design_fix1_axi_ooo_controller_0_0.sv" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_21  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_23  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_processing_system7_0_0/sim/design_fix1_processing_system7_0_0.v" \

vlog -work xlconstant_v1_1_10  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_0/sim/bd_4d46_one_0.v" \

vcom -work proc_sys_reset_v5_0_17 -93  -incr \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_1/sim/bd_4d46_psr0_0.vhd" \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_2/sim/bd_4d46_psr_aclk_0.vhd" \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_3/sim/bd_4d46_psr_aclk1_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_4/sim/bd_4d46_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_5/sim/bd_4d46_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_6/sim/bd_4d46_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_7/sim/bd_4d46_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_8/sim/bd_4d46_sarn_0.sv" \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_9/sim/bd_4d46_srn_0.sv" \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_10/sim/bd_4d46_sawn_0.sv" \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_11/sim/bd_4d46_swn_0.sv" \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_12/sim/bd_4d46_sbn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_13/sim/bd_4d46_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_14/sim/bd_4d46_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/sim/bd_4d46.v" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work axi_register_slice_v2_1_35  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_axi_smc_1/sim/design_fix1_axi_smc_1.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_clk_wiz_1/design_fix1_clk_wiz_1_clk_wiz.v" \
"../../../bd/design_fix1/ip/design_fix1_clk_wiz_1/design_fix1_clk_wiz_1.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_fix1/ip/design_fix1_rst_clk_wiz_100M_1/sim/design_fix1_rst_clk_wiz_100M_1.vhd" \
"../../../bd/design_fix1/ip/design_fix1_rst_ps7_0_50M_1/sim/design_fix1_rst_ps7_0_50M_1.vhd" \

vcom -work axi_bram_ctrl_v4_1_13 -93  -incr \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/2f03/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_fix1/ip/design_fix1_axi_bram_ctrl_0_1/sim/design_fix1_axi_bram_ctrl_0_1.vhd" \

vlog -work blk_mem_gen_v8_4_11  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a32c/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../bd/design_fix1/ipshared/cf53" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/ec67/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/6cfa/hdl" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/a9be" "+incdir+../../../../../../../../tools/xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_read" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo/axi_write" "+incdir+../../../../axifix1.gen/sources_1/bd/design_fix1/ipshared/cf53/axi_ooo" "+incdir+/home/minami/tools/xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_bram_ctrl_v4_1_13 -l blk_mem_gen_v8_4_11 \
"../../../bd/design_fix1/ip/design_fix1_blk_mem_gen_0_1/sim/design_fix1_blk_mem_gen_0_1.v" \
"../../../bd/design_fix1/sim/design_fix1.v" \

vlog -work xil_defaultlib \
"glbl.v"

