# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.srcs/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/design_fix1_axi_smc_1.xci
# IP: The module: 'design_fix1_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/bd_4d46.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_0/bd_4d46_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_1/bd_4d46_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_2/bd_4d46_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_3/bd_4d46_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_4/bd_4d46_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_5/bd_4d46_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_6/bd_4d46_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_7/bd_4d46_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_8/bd_4d46_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_9/bd_4d46_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_10/bd_4d46_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_11/bd_4d46_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_12/bd_4d46_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_13/bd_4d46_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_14/bd_4d46_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_1/bd_4d46_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_2/bd_4d46_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_3/bd_4d46_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_7/bd_4d46_s00a2s_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_8/bd_4d46_sarn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_9/bd_4d46_srn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_10/bd_4d46_sawn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_11/bd_4d46_swn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_12/bd_4d46_sbn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_13/bd_4d46_m00s2a_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fix1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fix1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.srcs/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/design_fix1_axi_smc_1.xci
# IP: The module: 'design_fix1_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/bd_4d46.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_0/bd_4d46_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_1/bd_4d46_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_2/bd_4d46_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_3/bd_4d46_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_4/bd_4d46_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_5/bd_4d46_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_6/bd_4d46_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_7/bd_4d46_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_8/bd_4d46_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_9/bd_4d46_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_10/bd_4d46_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_11/bd_4d46_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_12/bd_4d46_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_13/bd_4d46_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_14/bd_4d46_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_1/bd_4d46_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_2/bd_4d46_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_3/bd_4d46_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_7/bd_4d46_s00a2s_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_8/bd_4d46_sarn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_9/bd_4d46_srn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_10/bd_4d46_sawn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_11/bd_4d46_swn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_12/bd_4d46_sbn_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/bd_0/ip/ip_13/bd_4d46_m00s2a_0_ooc.xdc

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fix1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/minami/Coding_IPDesign/thesis_soc_proj/Vivado_projfile/axifix1/axifix1.gen/sources_1/bd/design_fix1/ip/design_fix1_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fix1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
